services:
  univaultoffice-documentserver:
    build:
      context: .
    image: univaultoffice/documentserver #[-de,-ee]
    container_name: univaultoffice-documentserver
    depends_on:
      - univaultoffice-postgresql
      - univaultoffice-rabbitmq
    environment:
      - DB_TYPE=postgres
      - DB_HOST=univaultoffice-postgresql
      - DB_PORT=5432
      - DB_NAME=univaultoffice
      - DB_USER=univaultoffice
      - AMQP_URI=amqp://guest:guest@univaultoffice-rabbitmq
      # Uncomment strings below to enable the JSON Web Token validation.
      #- JWT_ENABLED=true
      #- JWT_SECRET=secret
      #- JWT_HEADER=Authorization
      #- JWT_IN_BODY=true
    ports:
      - '80:80'
      - '443:443'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/info/info.json"]
      interval: 30s
      retries: 5
      start_period: 60s
      timeout: 10s
    stdin_open: true
    restart: always
    stop_grace_period: 60s
    volumes:
       - /var/www/univaultoffice/Data
       - /var/log/univaultoffice
       - /var/lib/univaultoffice/documentserver/App_Data/cache/files
       - /var/www/univaultoffice/documentserver-example/public/files
       - /usr/share/fonts
       
  univaultoffice-rabbitmq:
    container_name: univaultoffice-rabbitmq
    image: rabbitmq:3
    restart: always
    expose:
      - '5672'
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 10s
      retries: 3
      start_period: 10s
      timeout: 10s

  univaultoffice-postgresql:
    container_name: univaultoffice-postgresql
    image: postgres:15
    environment:
      - POSTGRES_DB=univaultoffice
      - POSTGRES_USER=univaultoffice
      - POSTGRES_HOST_AUTH_METHOD=trust
    restart: always
    expose:
      - '5432'
    volumes:
      - postgresql_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U univaultoffice"]
      interval: 10s
      retries: 3
      start_period: 10s
      timeout: 10s

volumes:
  postgresql_data:
